POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "Vanessa Samuel",
 "phoneNumber": "329434343",
 "email": "vanessamuel@gmail.com",
 "wage": 5500, 
 "sector": "Tecnologia" ,
 "status": "ATIVO"
 
}

###
GET http://localhost:3000/users
GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/b16ce1c6-7569-46c8-b1ad-2da7a01fa909

//

//HTTP EXPENSES

###
POST http://localhost:3000/expenses
Content-Type: application/json 

{
    "name": "Luz",
    "description": "Luz São Mateus",
    "value": 126.5,
    "type": "Variavel",
    "date": "2025-10-10"

}

###
GET http://localhost:3000/expenses

//Courses 

###
POST http://localhost:3000/courses
Content-Type: application/json

{
    "image": "fdgdfgdd",
    "status": "ATIVO",
    "name": "Java",
    "description": "Curso para quem quer aprender a progrmar com Java e SpringBoot",
    "value": 1500
}

###
GET http://localhost:3000/courses

###

DELETE http://localhost:3000/courses/27f2a25e-0972-4d4a-a3ab-775449989351

PUT http://localhost:3000/courses/
Content-Type: application/json

{
    "image": "fdgdfgdd",
    "status": "ATIVO",
    "name": "Java",
    "description": "Curso para quem quer aprender a progrmar com Java e SpringBoot",
    "value": 1500
}
###

DELETE http://localhost:3000/expenses/10bb5412-6c10-48c9-a33d-bcb0b9279bbd
###
PUT http://localhost:3000/expenses/46bee814-3aa6-461c-b335-472fc3e58bd7
Content-Type: application/json 

{
    "name": "Reabastecimento",
    "description": "Lanche",
    "value": 47.5,
    "type": "Variavel",
    "date": "2025-10-12"

}

###
GET http://localhost:3000/franchises

###
PUT http://localhost:3000/franchises/
Content-Type: application/json

{
    "name": "Unidade São Mateus",
    "city": "Juiz de Fora",
    "state": "Minas Gerais",
    "responsible":"Yuri",
    "phoneNumber": "311545454",
    "email": "codisaomateus@gmail.com",
    "status": "ATIVO"

}


DELETE http://localhost:3000/franchises/

