//HTTP COLLABORATOR

POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "Vanessa Samuel",
 "phoneNumber": "329434343",
 "email": "vanessamuel@gmail.com",
 "wage": 5500, 
 "sector": "Tecnologia" ,
 "status": "ATIVO"
 
}

###
GET http://localhost:3000/users

//

//HTTP EXPENSES

###
POST http://localhost:3000/expenses
Content-Type: application/json 

{
    "name": "Luz",
    "description": "Luz São Mateus",
    "value": 126.5,
    "type": "Variavel",
    "date": "2025-10-10"

}

###
GET http://localhost:3000/expenses

